rest:
  mapping:
    customer: /api/v1/customerManagement/customer
    customer.id: /api/v1/customerManagement/customer/{id} 
    
spring:
  data:
    mongodb:
      host: localhost
      port: 13454
#      authentication-database: heroku_wvq68bpf
#      username: heroku_wvq68bpf
#      password: heroku_wvq68bpf
      database: heroku_wvq68bpf